'use strict';
const TZ='America/New_York';
const $=id=>document.getElementById(id);
const dayFormat=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'});
const clockFormat=new Intl.DateTimeFormat('en-US',{timeZone:TZ,hour:'numeric',minute:'2-digit',hour12:true});
function tick(){const now=new Date();const hour=Number(new Intl.DateTimeFormat('en-US',{timeZone:TZ,hour:'numeric',hourCycle:'h23'}).format(now));$('greeting').textContent=hour<12?'Good morning,':hour<18?'Good afternoon,':'Good evening,';$('date').textContent=new Intl.DateTimeFormat('en-US',{timeZone:TZ,weekday:'short',month:'short',day:'numeric',year:'numeric'}).format(now);const parts=clockFormat.formatToParts(now);$('time').textContent=parts.filter(p=>p.type==='hour'||p.type==='minute'||p.type==='literal').map(p=>p.value).join('').trim();$('period').textContent=parts.find(p=>p.type==='dayPeriod').value;}
const descriptions={0:'Clear',1:'Mostly clear',2:'Partly cloudy',3:'Overcast',45:'Fog',48:'Freezing fog',51:'Light drizzle',53:'Drizzle',55:'Heavy drizzle',56:'Freezing drizzle',57:'Freezing drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',66:'Freezing rain',67:'Freezing rain',71:'Light snow',73:'Snow',75:'Heavy snow',77:'Snow grains',80:'Rain showers',81:'Rain showers',82:'Heavy showers',85:'Snow showers',86:'Heavy snow showers',95:'Thunderstorms',96:'Thunderstorms · hail',99:'Thunderstorms · hail'};
const number=v=>typeof v==='number'&&Number.isFinite(v)?Math.round(v)+'°':'—°';
const params=new URLSearchParams({latitude:'35.5849',longitude:'-80.8101',current:'temperature_2m,apparent_temperature,is_day,weather_code',daily:'temperature_2m_max,temperature_2m_min,precipitation_probability_max,sunrise,sunset',temperature_unit:'fahrenheit',timezone:TZ,timeformat:'unixtime',forecast_days:'2'});
const endpoint='https://api.open-meteo.com/v1/forecast?'+params;
let lastSuccess=0,lastData=null,busy=false;
function render(data){const c=data.current,d=data.daily;if(!c||!d||!Number.isFinite(c.temperature_2m))throw Error('Incomplete weather');const today=dayFormat.format(new Date());const i=d.time.findIndex(t=>dayFormat.format(new Date(t*1000))===today);if(i<0)throw Error('Forecast date unavailable');$('temperature').textContent=number(c.temperature_2m);$('feels').textContent=number(c.apparent_temperature);$('condition').textContent=descriptions[c.weather_code]||'Conditions unavailable';$('icon').textContent=c.weather_code<=1?(c.is_day?'☀':'☾'):c.weather_code<=3?'☁':c.weather_code>=95?'ϟ':c.weather_code>=71&&c.weather_code<=77?'❄':'☂';$('high').textContent=number(d.temperature_2m_max[i]);$('low').textContent=number(d.temperature_2m_min[i]);$('rain').textContent=typeof d.precipitation_probability_max[i]==='number'?d.precipitation_probability_max[i]+'%':'—%';for(const key of ['sunrise','sunset'])$(key).textContent=typeof d[key][i]==='number'?clockFormat.format(new Date(d[key][i]*1000)):'—';}
function status(){if(lastSuccess){const age=Date.now()-lastSuccess;$('status').textContent=(age>35*60*1000?'Weather delayed · ':'Updated ')+clockFormat.format(new Date(lastSuccess));}}
async function refresh(){if(busy)return;busy=true;try{const response=await fetch(endpoint,{signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error('Weather request failed');const data=await response.json();render(data);lastData=data;lastSuccess=Date.now();status();}catch(error){if(lastData){status();$('status').textContent='Weather delayed · last fetched '+clockFormat.format(new Date(lastSuccess));}else{$('condition').textContent='Weather unavailable';$('status').textContent='Weather unavailable · retrying shortly';}}finally{busy=false;}}
tick();setInterval(tick,1000);refresh();setInterval(refresh,15*60*1000);setInterval(status,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){tick();if(Date.now()-lastSuccess>15*60*1000)refresh();}});window.addEventListener('online',refresh);
